### ISSUE TITLE
Limit of ots_searchTransactionBefore of most recent 88k blocks

### ISSUE THREAD

**Issue by dreadedhamish** [otterscan/otterscan#1269]
I'm playing with the Otterscan API for the first time.

When using the endpoints ots_searchTransactionBefore and ots_searchTransactionAfter I am getting good results but only for the last 88929 blocks. If I query earlier than that I get Erigon crashes.

Query:
{
    "jsonrpc":"2.0", 
    "id": 1, 
    "method":"ots_searchTransactionsBefore",
    "params":[
        "0x7a20189B297343CF26d8548764b04891f37F3414", 18294312, 5
    ]
}

Here is the error from Erigon:

panic: runtime error: index out of range [26] with length 0
goroutine 712 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*OtterscanAPIImpl).traceBlock(0xc0006121f8, {0x2ca3630?, 0xc08d798e40}, {0x2c86340?, 0xc08d79cfa0}, 0x117217c?, {0x7a, 0x20, 0x18, 0x9b, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/otterscan_search_trace.go:99 +0x12f3
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*OtterscanAPIImpl).searchTraceBlock(0xc0006121f8, {0x2c86340, 0xc08d79cfa0}, 0x128a52e?, {0x7a, 0x20, 0x18, 0x9b, 0x29, 0x73, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/otterscan_search_trace.go:33 +0x206
 created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*OtterscanAPIImpl).traceBlocks
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/otterscan_api.go:451 +0xa7

Am I hitting a limit? Is this expected?

Environment:
Running latest erigon and otterscan (regular, not the custom build).
Chain - Pulsechain
Partial Archive Node - archive node since it forked at block 16492698

**Comment by wmitsuda** [comment]
hi, sorry for the delay.

I'm not sure about "partial archive node", is that some pulsechain mod?

**Comment by dreadedhamish** [comment]
> hi, sorry for the delay.
> 
> I'm not sure about "partial archive node", is that some pulsechain mod?

no, a 'partial archive node' is an Erigon function - using a 'prune' flag you are able to tell Erigon to be an archive node, but only for a specific range of blocks, for example: be an archive node but only from the merge.  A popular implementation is a 'recent archive node' where the most recent 90K blocks are stored.
